spring:
  application:
    name: spring_jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_jpa
    username: abidk
    password: 9579
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true